"use strict";
// Arbitrary-order protection completion: fix only logically forced added arcs.
const fs=require("fs"),path=require("path");
function demand(ok,s,data){if(!ok)throw Error(s+" "+JSON.stringify(data));}
function pc(m){let r=0;for(;m;m&=m-1)r++;return r;}
function ids(m,n){const r=[];for(let v=0;v<n;v++)if(m&(1<<v))r.push(v);return r;}
function graph(out){const n=out.length,full=(1<<n)-1,inc=Array(n).fill(0),two=Array(n).fill(0);for(let x=0;x<n;x++)for(const y of ids(out[x],n)){demand(x!==y&&!(out[y]&(1<<x)),"Oriented graph");inc[y]|=1<<x;two[x]|=out[y];}for(let x=0;x<n;x++)two[x]&=full&~(out[x]|1<<x);
 const far=out.map((m,x)=>full&~(m|two[x]|1<<x)),M=out.map((m,x)=>full&~(m|inc[x]|1<<x)),prot=far.map((m,x)=>ids(m,n).reduce((z,y)=>(out[y]&(1<<x))&&!(inc[y]&~inc[x])?z|1<<y:z,0)),forced=Array(n).fill(0);
 for(let w=0;w<n;w++)for(const a of ids(prot[w],n))forced[a]|=out[w]&M[a];
 return{out,n,full,inc,two,far,M,prot,forced,F:far.map((m,x)=>m&~prot[x]),gap:out.map((m,x)=>pc(m)-pc(two[x]))};}
function rank(d,reverse=false){let left=d.full;const r=Array(d.n);for(let i=0;left;i++){const avail=ids(left,d.n).filter(x=>!(d.prot[x]&left));demand(avail.length,"Protection poset is acyclic",d.out);const v=reverse?avail.at(-1):avail[0];r[v]=i;left&=~(1<<v);}return r;}
function completion(d,r){const T=d.out.slice();for(let a=0;a<d.n;a++)for(let b=a+1;b<d.n;b++)if(d.M[a]&(1<<b)){demand(!(d.forced[a]&(1<<b))||!(d.forced[b]&(1<<a)),"No conflicting forced pair",{out:d.out,a,b});const forward=(d.forced[a]&(1<<b))||(!(d.forced[b]&(1<<a))&&r[a]<r[b]);T[forward?a:b]|=1<<(forward?b:a);}return graph(T);}
const counts={graphsFive:0,randomGraphs:0,completions:0,protectedPairs:0,forcedArcs:0,releasedUniquelyConvenientArcs:0,vertexEnvelopes:0,exactBudgetIdentities:0,maximalCompletionTests:0,medianFeedsWithoutAddedOutarcs:0};
let deficientFeedControl=null,allMaxFeedControl=null;
function check(out,randomGraph=false){const d=graph(out),Q=graph(d.out.map((m,x)=>m|d.forced[x]));for(let x=0;x<d.n;x++)for(const y of ids(d.prot[x],d.n)){demand(!(Q.inc[y]&~Q.inc[x])&&!(Q.out[x]&~Q.out[y]),"Fixed partial Q supplies two-sided domination",{out,Q:Q.out,x,y});}
 for(let a=0;a<d.n;a++)for(const b of ids(d.forced[a],d.n)){demand(ids(d.inc[a],d.n).every(p=>d.out[p]&(1<<b)||d.two[p]&(1<<b)),"Forced direction convenient",{out,a,b});demand(ids(d.inc[b],d.n).some(p=>d.far[p]&(1<<a)),"Reverse forced direction nonconvenient",{out,a,b});counts.forcedArcs++;}
 for(const rev of [false,true]){const r=rank(d,rev),T=completion(d,r);counts.completions++;for(let x=0;x<d.n;x++){for(const y of ids(d.prot[x],d.n)){demand(!(T.inc[y]&~T.inc[x]),"Original protection retained",{out,T:T.out,x,y,r});counts.protectedPairs++;}
 const K=T.out[x]&~out[x],A=T.two[x]&d.far[x],cost=pc(K&d.F[x])+pc(A);demand(!(T.two[x]&~((d.two[x]|d.F[x])&~K)),"Unprotected-far envelope",{out,T:T.out,x,r});demand(T.gap[x]-d.gap[x]===2*pc(K)-cost,"Exact cost identity",{out,T:T.out,x,K,A,cost});demand(cost<=pc(d.F[x]),"Disjoint cost bounded by t");counts.vertexEnvelopes++;counts.exactBudgetIdentities++;
 for(const y of ids(K,d.n))if(!(d.forced[x]&(1<<y))){const forward=ids(d.inc[x],d.n).every(p=>!(d.far[p]&(1<<y))),backward=ids(d.inc[y],d.n).every(p=>!(d.far[p]&(1<<x)));if(!forward&&backward)counts.releasedUniquelyConvenientArcs++;}}
 }if(randomGraph)counts.randomGraphs++;else counts.graphsFive++;}
function allCompletions(d){const seen=new Map();function go(left,r){if(!left){const T=completion(d,r),key=T.out.join(",");if(!seen.has(key))seen.set(key,T);return;}const i=d.n-pc(left);for(const x of ids(left,d.n))if(!(d.prot[x]&left)){r[x]=i;go(left&~(1<<x),r);}}go(d.full,Array(d.n));return[...seen.values()];}
function median(T){const n=T.n,dp=Array(1<<n).fill(-1);dp[0]=0;for(let m=1;m<(1<<n);m++)for(const x of ids(m,n)){const old=m&~(1<<x);dp[m]=Math.max(dp[m],dp[old]+pc(T.inc[x]&old));}return{dp,score:dp.at(-1)};}
function maxAudit(out){const d=graph(out),all=allCompletions(d),best=Math.max(...all.map(T=>median(T).score)),feedSet=new Set(),Q=graph(d.out.map((m,x)=>m|d.forced[x])),qm=median(Q),released=d.M.reduce((s,m)=>s+pc(m),0)/2-d.forced.reduce((s,m)=>s+pc(m),0);demand(best===qm.score+released,"Fixed partial optimization identity",{out,best,partialMedianScore:qm.score,released});let firstMax=null;for(const T of all){const md=median(T);if(md.score!==best)continue;if(!firstMax)firstMax=T.out;
 function go(mask,after){if(!mask)return;for(const x of ids(mask,d.n)){const old=mask&~(1<<x);if(md.dp[old]+pc(T.inc[x]&old)!==md.dp[mask])continue;
 if(mask===d.full){feedSet.add(x);demand(T.out[x]===d.out[x],"Every maximum-family feed has no added outgoing arc",{out,T:T.out,x});counts.medianFeedsWithoutAddedOutarcs++;
  if(!deficientFeedControl&&d.gap[x]>0)deficientFeedControl={out,T:T.out,feed:x,originalGap:d.gap[x],completedGap:T.gap[x],t:pc(d.F[x]),newSecondHeads:ids(T.two[x]&d.far[x],d.n),medianScore:best};}
 // x precedes every vertex already in after. No free incoming arc may go backward.
 const freeIncoming=T.inc[x]&d.M[x]&~d.forced.reduce((m,_,a)=>d.forced[a]&(1<<x)?m|1<<a:m,0);demand(!(freeIncoming&after),"Every maximum-family median keeps free added arcs forward",{out,T:T.out,x,after});
 for(const y of ids(d.prot[x],d.n))demand(!(after&(1<<y)),"Every median extends protection",{out,T:T.out,x,y,after});go(old,after|1<<x);}}
 go(d.full,0);}const qfeeds=ids(d.full,d.n).filter(x=>qm.dp[d.full&~(1<<x)]+pc(Q.inc[x]&(d.full&~(1<<x)))===qm.score);demand(qfeeds.length===feedSet.size&&qfeeds.every(x=>feedSet.has(x)),"Q and optimizing completion family have exactly the same possible feeds",{out,qfeeds,feedSet:[...feedSet]});for(const f of qfeeds)demand(Q.out[f]===d.out[f]&&Q.two[f]===d.two[f],"Both Q-feed neighborhoods exactly equal original",{out,Q:Q.out,f});if(!allMaxFeedControl&&[...feedSet].every(x=>d.gap[x]>0))allMaxFeedControl={out,firstMaxCompletion:firstMax,allPossibleMaxFamilyFeeds:[...feedSet],originalGaps:d.gap,medianScore:best};counts.maximalCompletionTests++;}
for(let code=0;code<59049;code++){let q=code;const out=Array(5).fill(0);for(let a=0;a<5;a++)for(let b=a+1;b<5;b++){const z=q%3;q=Math.floor(q/3);if(z===1)out[a]|=1<<b;if(z===2)out[b]|=1<<a;}check(out);}
let seed=0x5106f0ce;function random(){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296;}
for(let s=0;s<20000;s++){const n=6+s%7,out=Array(n).fill(0),density=[.25,.45,.65,.85][s%4];for(let a=0;a<n;a++)for(let b=a+1;b<n;b++)if(random()<density){if(random()<.5)out[a]|=1<<b;else out[b]|=1<<a;}check(out,true);if(s<300)maxAudit(out.slice(0,6).map(m=>m&63));}
// Releasing every uniquely convenient direction would be invalid.
const naive=graph([4,1,0]),r=[2,1,0],bad=naive.out.slice();bad[2]|=1<<1;const failed=graph(bad);demand(naive.prot[0]&(1<<1),"Naive control originally protected");demand(failed.two[0]&(1<<1),"Naive all-free completion destroys protection");
// But the earlier canonical-only obstruction really disappears in the enlarged family.
const control=graph([0,49,51,6,9,8]);demand(control.forced.every(m=>m===0),"Canonical obstruction has no protection-forced missing pair");const cr=[5,2,1,0,3,4],ct=completion(control,cr);demand(ct.out[0]===0,"Enlarged reference can make original sink0 remain sink");
// Exact unweighted blow-up of the Havet--Thomasse weighted four-cycle warning.
const cycleClasses=[[0,1,2],[3,4],[5,6,7,8],[9]],cycleOut=Array(10).fill(0);for(let a=0;a<4;a++)for(const x of cycleClasses[a])for(const y of cycleClasses[(a+1)%4])cycleOut[x]|=1<<y;
const cd=graph(cycleOut),cmed=median(cd),cfull=cd.full,possibleFeeds=ids(cfull,10).filter(x=>cmed.dp[cfull&~(1<<x)]+pc(cd.inc[x]&(cfull&~(1<<x)))===cmed.score),ways=Array(1<<10).fill(0);ways[0]=1;
for(let mask=1;mask<=cfull;mask++)for(const x of ids(mask,10)){const old=mask&~(1<<x);if(cmed.dp[old]+pc(cd.inc[x]&old)===cmed.dp[mask])ways[mask]+=ways[old];}
const cT=completion(cd,Array.from({length:10},(_,i)=>i));demand(cd.prot.every(m=>m===0)&&cd.forced.every(m=>m===0),"Four-cycle clone has no original protection");demand(cmed.score===18&&ways[cfull]===288&&possibleFeeds.join(",")==="9","Exact median obstruction count");demand(pc(cd.out[9])===3&&pc(cd.two[9])===2&&cd.gap[9]===1&&pc(cd.F[9])===4,"Original deficient feed");demand(cT.out[9]===cd.out[9]&&cT.gap[9]===-3&&median(cT).score===42,"Maximum enlarged completion still deficient in original graph");
let p9=0;for(let x=0;x<10;x++)if(cd.far[x]&(1<<9))p9++;const eta9=2*pc(cd.M[9])+cd.gap[9]-1-p9;demand(eta9===1,"Control violates only minimal unit budget, not formal residual value");
const fourCycleCloneControl={classSizes:[3,2,4,1],out:cycleOut,originalGaps:cd.gap,completion:cT.out,medianScoreD:cmed.score,medianScoreT:42,medianOrdersD:ways[cfull],allMaxFamilyFeeds:possibleFeeds,feed:9,first:ids(cd.out[9],10),second:ids(cd.two[9],10),newSecondHeads:ids(cT.two[9]&cd.far[9],10),feedResidual:eta9,feedUnprotectedFarBudget:pc(cd.F[9])};
const ud=graph([30,224,96,96,2,320,1,1,1]),uq=graph(ud.out.map((m,x)=>m|ud.forced[x])),um=median(uq),uorder=[4,1,2,3,5,6,7,8,0],urank=Array(9);uorder.forEach((x,i)=>urank[x]=i);const ut=completion(ud,urank);let pu=0;for(let x=0;x<9;x++)if(ud.far[x]&1)pu++;const eu=2*pc(ud.M[0])+ud.gap[0]-1-pu;
demand(um.score===17&&um.dp[ud.full&~1]+pc(uq.inc[0]&(ud.full&~1))===um.score,"Unit feed is global Q median feed");demand(eu===1&&pc(ud.F[0])===1&&ud.gap[0]===1,"Unit feed has eta=t=g=1");demand(ut.out[0]===ud.out[0]&&ut.gap[0]===0&&median(ut).score===um.score+36-uq.out.reduce((s,m)=>s+pc(m),0),"Unit feed saturates SNP after completion");demand(ud.forced[5]&1,"Missing reverse witness is protection-forced");
const unitFeedForcedWitnessControl={out:ud.out,Q:uq.out,completion:ut.out,medianOrder:uorder,medianScoreQ:um.score,feed:0,originalFirst:ids(ud.out[0],9),originalSecond:ids(ud.two[0],9),newSecondHeads:ids(ut.two[0]&ud.far[0],9),feedResidual:eu,feedUnprotectedFarBudget:1,originalFeedGap:1,completedFeedGap:0,forcedIncomingWitness:[5,0],forcingProtectedPair:[5,6],otherSeymourVertices:ud.gap.map((g,x)=>g<=0?x:null).filter(x=>x!==null)};
const result={status:"PASS",counts,deficientFeedControl,allMaxFeedControl,fourCycleCloneControl,unitFeedForcedWitnessControl,naiveControl:{out:naive.out,protection:[1,0],naiveReferenceRank:r,badCompletion:bad,forcedDirections:naive.forced},releasedCanonicalObstruction:{out:control.out,referenceRank:cr,completion:ct.out,feedZero:0,budget:0},limits:["Exact graph-level checks verify protection and local identities, not the all-deficient global completion-selection theorem.","The all-order lemma and maximal-completion proof are separate from finite checking.","Releasing a uniquely-convenient direction loses its convenience, so earlier direct-transfer feed theorems cannot be used without rechecking hypotheses."]};fs.writeFileSync(path.join(__dirname,"audit_protection_forced_completion.results.json"),JSON.stringify(result,null,2)+"\n");console.log(JSON.stringify(result,null,2));
