"use strict";
// Independent verifier: no LP/SAT solver, no generator helper, exact integer arithmetic.
const fs=require("fs"),path=require("path"),crypto=require("crypto");
function ok(v,s,d){if(!v)throw Error(s+" "+JSON.stringify(d));}
function bitCount(m){let c=0;while(m){m&=m-1;c++;}return c;}
function decode(n,code){const out=Array(n).fill(0);let z=code;for(let a=0;a<n;a++)for(let b=a+1;b<n;b++){const t=z%3;z=Math.floor(z/3);if(t===1)out[a]|=1<<b;else if(t===2)out[b]|=1<<a;}return out;}
function incoming(out){const n=out.length,I=Array(n).fill(0);for(let i=0;i<n;i++)for(let j=0;j<n;j++)if(out[i]&(1<<j)){ok(i!==j&&!(out[j]&(1<<i)),"Core not oriented",{out,i,j});I[j]|=1<<i;}return I;}
function mass(P,w){let r=0;for(let i=0;i<w.length;i++)if(P&(1<<i))r+=w[i];return r;}
function check(n,out,w){const I=incoming(out),full=(1<<n)-1;ok(w.length===n&&w.every(x=>Number.isSafeInteger(x)&&x>=0)&&w.reduce((s,x)=>s+x,0)>0,"Invalid integer density",{n,out,w});let patterns=0;
 for(let P=0;P<=full;P++)if(I.some(J=>(P&~J)===0)){let R=0;for(let i=0;i<n;i++)if(!(P&(1<<i))&&(out[i]&P))R|=1<<i;ok(mass(R,w)>=mass(P,w),"Pattern inequality fails",{n,out,w,P,R});patterns++;}return patterns;}
const counts={coresByOrder:{},totalCores:0,patternChecks:0,nonuniformFiveCertificates:0,maxWeight:0,maxDenominator:0},hashes=[];
const own=JSON.parse(fs.readFileSync(path.join(__dirname,"incoming_pattern_certificates_le4.json"),"utf8"));
for(let n=1;n<=3;n++){const records=own.certificates.filter(x=>x.n===n),expected=3**(n*(n-1)/2);ok(records.length===expected,"Small prefix coverage",{n});const indexed=new Map(records.map(x=>[x.code,x]));ok(indexed.size===expected,"Duplicate prefix codes");for(let code=0;code<expected;code++){const rec=indexed.get(code),out=decode(n,code);ok(rec&&rec.out.join(",")===out.join(","),"Prefix encoding",{n,code});counts.patternChecks+=check(n,out,rec.weights);counts.totalCores++;}counts.coresByOrder[n]=expected;}
for(const n of [4,5]){const filename="incoming_core_certificates_n"+n+".json",raw=fs.readFileSync(path.join(__dirname,filename)),table=JSON.parse(raw),expected=3**(n*(n-1)/2);ok(table.n===n&&table.certificates.length===expected,"Exact table coverage",{n,expected,actual:table.certificates.length});
 hashes.push({file:filename,sha256:crypto.createHash("sha256").update(raw).digest("hex")});for(let code=0;code<expected;code++){const out=decode(n,code),w=table.certificates[code];ok(w.every(x=>x===0||x===1||(n===5&&x===3)),"Claimed exact weight alphabet",{n,code,w});counts.patternChecks+=check(n,out,w);counts.maxWeight=Math.max(counts.maxWeight,...w);counts.maxDenominator=Math.max(counts.maxDenominator,w.reduce((s,x)=>s+x,0));if(n===5&&new Set(w.filter(x=>x>0)).size>1)counts.nonuniformFiveCertificates++;counts.totalCores++;}counts.coresByOrder[n]=expected;}
// Independently test the labelled-pattern construction identity, without claiming its gaps positive.
let state=0x5300fa4a;function random(){state^=state<<13;state^=state>>>17;state^=state<<5;return(state>>>0)/4294967296;}
let constructions=0,constructionVertexChecks=0,entireMaximalClassChecks=0,constructedGraphsLargerThanFive=0;
for(let sample=0;sample<500;sample++){const k=1+sample%5,H=decode(k,Math.floor(random()*3**(k*(k-1)/2))),I=incoming(H),patterns=[];for(let P=0;P<(1<<k);P++)if(I.some(J=>!(P&~J)))patterns.push(P);
 const copies=[],multiplicities=new Map();for(let t=0;t<3;t++){const P=patterns[Math.floor(random()*patterns.length)],w=1+Math.floor(random()*2);multiplicities.set(P,(multiplicities.get(P)||0)+w);}const vertices=I.map((P,label)=>({P,label})),K=2;
 for(const[P,w]of multiplicities)for(let c=0;c<K*w;c++){const allowed=I.map((J,j)=>!(P&~J)?j:-1).filter(j=>j>=0);vertices.push({P,label:allowed[Math.floor(random()*allowed.length)]});}
 const n=vertices.length,out=Array(n).fill(0);for(let v=0;v<n;v++)for(let u=0;u<n;u++)if(vertices[u].P&(1<<vertices[v].label))out[v]|=1<<u;const incomingD=incoming(out),gaps=Array(n);
 const gamma=Array(k).fill(0),twoH=H.map((O,i)=>{let r=0;for(let j=0;j<k;j++)if(O&(1<<j))r|=H[j];return r&~(O|1<<i);}),gH=H.map((O,i)=>bitCount(O)-bitCount(twoH[i]));
 for(const[P,w]of multiplicities)for(let i=0;i<k;i++)gamma[i]+=w*((P&(1<<i))?1:(!(P&(1<<i))&&(H[i]&P))?-1:0);
 for(let v=0;v<n;v++){let two=0;for(let u=0;u<n;u++)if(out[v]&(1<<u))two|=out[u];two&=~(out[v]|1<<v);const gap=bitCount(out[v])-bitCount(two),i=vertices[v].label;gaps[v]=gap;ok(gap===K*gamma[i]+gH[i],"Labelled counterconstruction gap identity",{H,I,multiplicities:[...multiplicities],v,i,gap,expected:K*gamma[i]+gH[i],vertices});constructionVertexChecks++;}
 const classes=new Map();incomingD.forEach((P,v)=>{if(!classes.has(P))classes.set(P,[]);classes.get(P).push(v);});const maximal=[...classes.entries()].filter(([P])=>![...classes.keys()].some(J=>J!==P&&!(P&~J)));ok(maximal.length<=k,"Constructed graph maximal-class cover",{H,maximalClasses:maximal.length,k});ok(maximal.some(([,members])=>members.every(v=>gaps[v]<=0)),"An entire maximal incoming class is Seymour",{H,out,gaps,maximal});entireMaximalClassChecks++;if(n>5)constructedGraphsLargerThanFive++;constructions++;}
counts.nonemptyPatternChecks=counts.patternChecks-counts.totalCores;
const result={status:"PASS",counts,hashes,constructionChecks:{graphs:constructions,vertices:constructionVertexChecks,entireMaximalClassChecks,graphsLargerThanFive:constructedGraphsLargerThanFive},scope:"All 59,809 labelled oriented cores of orders 1..5 and every allowed pattern independently verified with nonnegative integer weights. No LP solver or floating arithmetic. Finite core certificate theorem applies to arbitrary-order containing graphs; it is not a full SNC proof. Labelled construction checks verify identities and the complete-Seymour-class conclusion, not a positive-gap counterexample."};
fs.writeFileSync(path.join(__dirname,"verify_incoming_pattern_tables_integer.results.json"),JSON.stringify(result,null,2)+"\n");console.log(JSON.stringify(result,null,2));
