"use strict";
// Exact graph and subset-DP adversarial audit, no external package.
const fs=require("fs"),path=require("path");
function demand(ok,s,data){if(!ok)throw Error(s+" "+JSON.stringify(data));}
function pc(m){let r=0;for(;m;m&=m-1)r++;return r;}
function ids(m,n){const a=[];for(let v=0;v<n;v++)if(m&(1<<v))a.push(v);return a;}
function graph(out){const n=out.length,full=(1<<n)-1,inc=Array(n).fill(0),two=Array(n).fill(0);for(let x=0;x<n;x++)for(const y of ids(out[x],n)){demand(x!==y&&!(out[y]&(1<<x)),"Oriented graph");inc[y]|=1<<x;two[x]|=out[y];}for(let x=0;x<n;x++)two[x]&=full&~(out[x]|1<<x);
 const far=out.map((m,x)=>full&~(m|two[x]|1<<x)),M=out.map((m,x)=>full&~(m|inc[x]|1<<x)),prot=far.map((m,x)=>ids(m,n).reduce((z,y)=>(out[y]&(1<<x))&&!(inc[y]&~inc[x])?z|1<<y:z,0)),forced=Array(n).fill(0);
 for(let w=0;w<n;w++)for(const a of ids(prot[w],n))forced[a]|=out[w]&M[a];
 return{out,n,full,inc,two,far,M,prot,forced,F:far.map((m,x)=>m&~prot[x]),gap:out.map((m,x)=>pc(m)-pc(two[x]))};}
function closure(out,trace=false){let Q=graph(out),rounds=0;const stages=[Q],addedTails=new Set();while(Q.forced.some(m=>m)){demand(rounds<Q.n*(Q.n-1)/2,"Finite termination");for(let a=0;a<Q.n;a++)for(const b of ids(Q.forced[a],Q.n)){demand(!(Q.forced[b]&(1<<a)),"No conflicting force",{out:Q.out,a,b});demand(ids(Q.inc[a],Q.n).every(v=>!(Q.far[v]&(1<<b))),"Each current forced direction is current-convenient",{out:Q.out,a,b});addedTails.add(a);}
 const R=graph(Q.out.map((m,x)=>m|Q.forced[x]));for(let x=0;x<Q.n;x++)for(const y of ids(Q.prot[x],Q.n))demand((R.out[y]&(1<<x))&&!(R.inc[y]&~R.inc[x]),"Every stage preserves every current protection",{old:Q.out,next:R.out,x,y});Q=R;stages.push(Q);rounds++;}
 for(let x=0;x<Q.n;x++)for(const y of ids(Q.prot[x],Q.n))demand(!(Q.out[x]&~Q.out[y]),"Stable current protection has full outgoing nesting",{out:Q.out,x,y});return{Q,rounds,stages,addedTails};}
function medians(Q){const n=Q.n,dp=Array(1<<n).fill(0);for(let m=1;m<(1<<n);m++)for(const x of ids(m,n)){const old=m&~(1<<x);dp[m]=Math.max(dp[m],dp[old]+pc(Q.inc[x]&old));}const feeds=ids(Q.full,n).filter(x=>dp[Q.full&~(1<<x)]+pc(Q.inc[x]&(Q.full&~(1<<x)))===dp[Q.full]);return{dp,feeds,score:dp.at(-1)};}
const counts={allFiveVertexGraphs:0,randomGraphs:0,explicitControlGraphs:0,totalStages:0,closureAddedArcs:0,maximumRounds:0,medianFeeds:0,positiveOriginalGapFeeds:0,strictOriginalFarSurpluses:0,feedStageNeighborhoodEqualities:0,originalBalancedFeedsRemoved:0,stableMissingMatchingGraphs:0,stableMatchingMedianFeeds:0,stableMatchingPositiveFeedCount:0};
let stableMatchingPositiveFeedControl=null,stableMatchingAllPositiveFeedsControl=null;
function audit(out,isRandom=false){const D=graph(out),c=closure(out),m=medians(c.Q),matching=c.Q.M.every(z=>pc(z)<=1);if(matching){counts.stableMissingMatchingGraphs++;counts.stableMatchingMedianFeeds+=m.feeds.length;}counts.totalStages+=c.rounds;counts.maximumRounds=Math.max(counts.maximumRounds,c.rounds);counts.closureAddedArcs+=c.Q.out.reduce((s,q,x)=>s+pc(q&~out[x]),0);
 for(const f of m.feeds){demand(!c.addedTails.has(f),"Final median feed is no closure-added tail",{out,Q:c.Q.out,f});for(const S of c.stages){demand(S.out[f]===out[f]&&S.two[f]===D.two[f],"Original first and exact-second feed sets survive every closure stage",{out,Q:S.out,f});counts.feedStageNeighborhoodEqualities++;}
  counts.medianFeeds++;if(D.gap[f]>0){counts.positiveOriginalGapFeeds++;demand(pc(D.F[f])>=D.gap[f]+1,"Strict ORIGINAL far-head surplus at every final partial median feed",{out,Q:c.Q.out,f,g:D.gap[f],t:pc(D.F[f])});counts.strictOriginalFarSurpluses++;if(matching){counts.stableMatchingPositiveFeedCount++;if(!stableMatchingPositiveFeedControl)stableMatchingPositiveFeedControl={original:out,Q:c.Q.out,missingPartners:c.Q.M.map(z=>ids(z,c.Q.n)),feed:f,originalGap:D.gap[f],feeds:m.feeds,allFeedGaps:m.feeds.map(v=>D.gap[v])};}}}
 if(matching&&m.feeds.every(f=>D.gap[f]>0)&&!stableMatchingAllPositiveFeedsControl)stableMatchingAllPositiveFeedsControl={original:out,Q:c.Q.out,feeds:m.feeds,allFeedGaps:m.feeds.map(v=>D.gap[v])};
 const first=graph(out.map((q,x)=>q|D.forced[x])),initial=medians(first);for(const f of initial.feeds)if(D.gap[f]>0&&pc(D.F[f])===D.gap[f]&&!m.feeds.includes(f))counts.originalBalancedFeedsRemoved++;
 if(isRandom)counts.randomGraphs++;else counts.allFiveVertexGraphs++;return{original:D,closure:c,median:m};}
for(let code=0;code<59049;code++){let q=code;const out=Array(5).fill(0);for(let a=0;a<5;a++)for(let b=a+1;b<5;b++){const z=q%3;q=Math.floor(q/3);if(z===1)out[a]|=1<<b;if(z===2)out[b]|=1<<a;}audit(out);}
let seed=0x5200c105;function random(){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296;}
for(let s=0;s<20000;s++){const n=6+s%7,out=Array(n).fill(0),density=[.25,.45,.65,.85][s%4];for(let a=0;a<n;a++)for(let b=a+1;b<n;b++)if(random()<density){if(random()<.5)out[a]|=1<<b;else out[b]|=1<<a;}audit(out,true);}
const controls=[];for(const out of [[30,224,96,96,2,320,1,1,1],[24,24,24,480,480,512,512,512,512,7]]){const a=audit(out,true);counts.randomGraphs--;counts.explicitControlGraphs++;controls.push({out,originalGaps:a.original.gap,originalFarBudgets:a.original.F.map(pc),closureRounds:a.closure.rounds,closureStages:a.closure.stages.map(s=>s.out),finalPartialFeeds:a.median.feeds,finalMedianScore:a.median.score});}
demand(counts.maximumRounds>=2,"Iterated rather than one-pass force exercised",counts);
const result={status:"PASS",counts,stableMatchingPositiveFeedControl,stableMatchingAllPositiveFeedsControl,controls,limits:["All arithmetic is exact integer arithmetic.","Graphs are arbitrary and not assumed all-deficient, strongly connected, or minimal.","The check verifies the all-order theorem's strict ORIGINAL surplus, not existence of any conjecture counterexample.","The ten-vertex four-cycle clone has empty closure and still a positive original-gap median feed: the remaining strict-surplus obstacle is real.","Absence of a deficient stable-matching feed in this sample is not a proof of that stronger candidate."]};fs.writeFileSync(path.join(__dirname,"audit_iterated_forced_feed_surplus.results.json"),JSON.stringify(result,null,2)+"\n");console.log(JSON.stringify(result,null,2));
